---
title: "DH – rvest, Boder transcripts"
author: "Simran Vatsa"
date: "10/1/2018"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(glue)
library(tidytext)
library(readr)
```

```{r}
## scraping the site
home <- read_html("http://voices.iit.edu/search_results?filter_by=name")
names <- home %>% 
  html_nodes(".result_list a") %>% 
  html_text()
names <- gsub("\\n", "", names)
names <- trimws(names)

english <- read_html("http://voices.iit.edu/search_results.php?filter_by=broadcast_lang&filter_value=English")
english_speakers <- english %>% 
  html_nodes(".result_list a") %>% 
  html_text()
english_speakers <- gsub("\\n", "", english_speakers)
english_speakers <- trimws(english_speakers)
wrongly_listed <- c("Charles Jean", "Jean Kahn", "Louis Kahn", "Anne Marcelle Kahn", "Abraham Schrameck", "János Deutsch", "Fira Monk")

nonenglish <- setdiff(names, english_speakers)
nonenglish <- c(nonenglish, wrongly_listed)
english_speakers <- setdiff(english_speakers, wrongly_listed)

main <- html_session("http://voices.iit.edu/search_results?filter_by=name")
transcripts <- rep(NA, 118)

for(i in 1:110) {
  transcripts[i] <- main %>% 
    follow_link(nonenglish[i]) %>% 
    follow_link("Read English Translation") %>% 
    html_nodes("ul:nth-child(3)") %>% 
    html_text()
}

for(i in 111:118) {
  transcripts[i] <- main %>% 
    follow_link(english_speakers[i-110]) %>% 
    follow_link("Read Transcript") %>% 
    html_nodes("ul:nth-child(3)") %>% 
    html_text()
}
```


```{r}
## processing/tidying text for combined .txt/.doc file + separate .txt files
write("Boder transcripts and translations\n", "Boder_transcripts.txt")
for(i in 1:118) {
  transcripts[i] <- gsub(" {2,}", " ", transcripts[i])
  transcripts[i] <- str_split(transcripts[i], "(\\n ){4}")
  transcripts[[i]] <- gsub("\\n", "", transcripts[[i]])
  transcripts[[i]] <- gsub(" {2,}", " ", transcripts[[i]])
  write(transcripts[[i]], "Boder_transcripts.txt", append = TRUE)
  write(transcripts[[i]], paste0("Boder_transcripts",i,".txt"))
}
```


```{r}
## processing/tidying for dataframe
transcripts_dataframe <- data.frame(speech = transcripts[[1]], 
                                    interviewee = rep(1, length(transcripts[[1]])), stringsAsFactors = FALSE)

for(i in 2:118){
  for(j in 1:length(transcripts[[i]])){
    transcripts_dataframe <- rbind(transcripts_dataframe, c(transcripts[[i]][j], i))
  } 
}

all_speakers <- c(nonenglish, english_speakers)
transcripts_dataframe$interviewee <- as.numeric(transcripts_dataframe$interviewee)
transcripts_dataframe$interviewee_name <- all_speakers[transcripts_dataframe$interviewee]

pos <- NA
speaker <- NA
words <- NA

for(i in 1:dim(transcripts_dataframe)[1]) {
  pos[i] <- regexpr(':', transcripts_dataframe$speech[i])
  speaker[i] <- substr(transcripts_dataframe$speech[i], 1, pos[i]-1)
  words[i] <- substr(transcripts_dataframe$speech[i], pos[i]+2, 10000)
}

transcripts_dataframe <- data.frame(transcripts_dataframe, speaker, words, stringsAsFactors = FALSE)
transcripts_dataframe <- transcripts_dataframe[-c(1,2)]
transcripts_dataframe$speaker <- trimws(transcripts_dataframe$speaker)

# write.csv(transcripts_dataframe, "Boder transcripts.csv", row.names = FALSE)
```

```{r}
# question-answer word ratio in Boder
transcripts_dataframe <- read.csv("Boder transcripts.csv", stringsAsFactors = FALSE)
boder_words <- transcripts_dataframe %>% filter(speaker == "David Boder")
boder_words$words <- gsub("\\[.*?\\]", " ", boder_words$words)
boder_words <- boder_words %>% unnest_tokens(word, words)

other_words <- transcripts_dataframe %>% filter(speaker != "David Boder")
other_words$words <- gsub("\\[.*?\\]", " ", other_words$words)
other_words <- other_words %>% unnest_tokens(word, words)

dim(other_words)[1]/dim(boder_words)[1]
```


```{r}
# extracting questions
questions <- NA
boder_lines <- transcripts_dataframe %>% filter(speaker == "David Boder")
boder_lines <- glue_collapse(boder_lines$words, sep = " ")
questions <- str_extract_all(boder_lines, "[A-Z][\\w\\s]+\\?")
questions <- questions[[1]]
questions <- data.frame(questions, stringsAsFactors = FALSE)
```

```{r  tidy=TRUE, tidy.opts=list(width.cutoff=60), warning=FALSE, message=FALSE, echo = FALSE, fig.height=1.5, fig.width=10}
# lexical dispersion plots
transcripts_dataframe <- read.csv("Boder transcripts.csv", stringsAsFactors = FALSE)
list_interviewees <- unique(transcripts_dataframe$interviewee_name)
list_interviewees <- list_interviewees[which(list_interviewees != "David Hirsch")]
list_interviewees <- sort(list_interviewees)
individual_interviewee <- c()
aberrations <- c(62,63,75,84,85,91,92,95)
setdiff(28:117, aberrations)


dispersion_plot <- function(vec_num, vec_col) {
  for(i in vec_num) {
    individual_interviewee <- transcripts_dataframe %>%   
    filter(interviewee_name == list_interviewees[i]) %>% 
    unnest_tokens(word, words) %>% mutate(rownum = row_number())
  
    total_words <- dim(individual_interviewee)[1]
    print(ggplot(individual_interviewee, 
          aes(x = rownum/total_words, xend = rownum/total_words, y = 2, yend = 1, color = speaker)) + 
    geom_segment(alpha = 0.8) +
    scale_color_manual(values = vec_col) +
    labs(y = '', x = '\nInterview progression') +
    theme(axis.text.y = element_blank(), panel.background = element_rect(fill = "white"), 
          axis.ticks.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) )
  }
}

dispersion_plot(c(1:9, 11:27), c("snow", "lightpink2", "palevioletred3", "rosybrown3"))
dispersion_plot(setdiff(28:117, aberrations), c("lightpink2", "snow", "palevioletred3", "rosybrown3"))
dispersion_plot(aberrations, c("lightpink2", "palevioletred3", "snow", "rosybrown3"))
dispersion_plot(10, c("snow", "palevioletred3", "lightpink2", "rosybrown3"))
dispersion_plot(41,  c("palevioletred3", "lightpink2", "snow"))

```


